name: FlashPresent
author: flash1110
version: 1.0
main: me.flash1110.christmas.FlashChristmas
description: Present for Cowsook 

commands:
  present:
    description: La command
    aliases: [presents, christmas, chanukah, hannukah]